# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages


before_deploy:
  - Rscript -e 'remotes::install_github("lockedatapublished/lockedatapkg")'
  - Rscript -e 'install.packages("pkgdown")'


deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
  skip_cleanup: true

after_success:
  - Rscript -e 'library(covr);coveralls(coverage = print(package_coverage(quiet = FALSE)))'

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
